# Test the documentation on SSH hardening
task:
  matrix:
    - name: 12.3-RELEASE
      freebsd_instance:
        image_family: freebsd-12-3
    - name: 12.4-RELEASE
      freebsd_instance:
        image_family: freebsd-12-4
    - name: 13.1-RELEASE
      freebsd_instance:
        image_family: freebsd-13-1
    - name: 13.2-RELEASE
      freebsd_instance:
        image_family: freebsd-13-2
    - name: 14.0-CURRENT
      freebsd_instance:
        image_family: freebsd-14-0-snap
  ssh-hardening_script:
    - sed -i '' 's/^/#/' README.md
    - sed -i '' '/^#         .*$/d' README.md
    - sed -i '' 's/^#    //' README.md
    - printf "#\!/bin/sh\nset -e\n%s\n" "$(cat README.md)" > ssh-hardening.sh
    - sh ./ssh-hardening.sh
  always:
    ssh-audit.out_artifacts:
      path: ssh-audit.out
      type: text/plain
